// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBheDLrbg_3GOODxop7b5zLXAIzyAy7-RQ',
    appId: '1:445075982399:web:a7b1dda11033ce54bed08a',
    messagingSenderId: '445075982399',
    projectId: 'cuisineapp-5d031',
    authDomain: 'cuisineapp-5d031.firebaseapp.com',
    storageBucket: 'cuisineapp-5d031.firebasestorage.app',
    measurementId: 'G-QQLKW7G1MW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbIxVlHUx3HgbxwbhlRnbmdVp8Ea0N6YE',
    appId: '1:445075982399:android:ca0a95e182b94f85bed08a',
    messagingSenderId: '445075982399',
    projectId: 'cuisineapp-5d031',
    storageBucket: 'cuisineapp-5d031.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBychNvcov8q1kJ7MqvCzF2XFJDS1OfmwM',
    appId: '1:445075982399:ios:f37300a4ee93e874bed08a',
    messagingSenderId: '445075982399',
    projectId: 'cuisineapp-5d031',
    storageBucket: 'cuisineapp-5d031.firebasestorage.app',
    iosBundleId: 'com.example.apprecette',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBychNvcov8q1kJ7MqvCzF2XFJDS1OfmwM',
    appId: '1:445075982399:ios:f37300a4ee93e874bed08a',
    messagingSenderId: '445075982399',
    projectId: 'cuisineapp-5d031',
    storageBucket: 'cuisineapp-5d031.firebasestorage.app',
    iosBundleId: 'com.example.apprecette',
  );
}
